# Generated by Django 3.2.13 on 2022-06-10 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20220610_0452'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Person',
        ),
        migrations.RenameField(
            model_name='userfile',
            old_name='uploaded_at',
            new_name='time_registered',
        ),
    ]
